name = "RayTracing"
uuid = "ca25e170-1634-4470-9d17-74c4669b51b1"
authors = ["Jessica Kent", "Ted Marku"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
